dataset:
  path: "SeaLab/Fusion360"
  token: "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"
  split: "train"
  keep_in_memory: False
  # revision: "f4fa0efa9af7f7c19088803ecbaa7bb95d37c8f1"
transforms:
  - _target_: pc_sam.datasets.transforms.NormalizePoints
  - _target_: pc_sam.datasets.transforms.NormalizeColor
    mean: 0.5
    std: 0.5
  - _target_: pc_sam.datasets.transforms.RandomSampleMask
    num_samples: 2
  - _target_: pc_sam.datasets.transforms.RandomSample
    num_samples: ${num_samples}
  - _target_: pc_sam.datasets.transforms.RandomScale
    low: 0.8
    high: 1.0
  - _target_: pc_sam.datasets.transforms.RandomRotatePerbuate
  - _target_: pc_sam.datasets.transforms.RandomRotateAlongAxis
  - _target_: pc_sam.datasets.transforms.ToTensor